python ./example1_datasets.py 
No GPU was detected! This notebook can be *very* slow without a GPU üê¢
Using transformers v4.16.2
Using datasets v1.16.1
Traceback (most recent call last):
  File "/usr/local/anaconda3/lib/python3.11/site-packages/matplotlib/style/core.py", line 137, in use
    style = _rc_params_in_file(style)
            ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/anaconda3/lib/python3.11/site-packages/matplotlib/__init__.py", line 866, in _rc_params_in_file
    with _open_file_or_url(fname) as fd:
  File "/usr/local/anaconda3/lib/python3.11/contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "/usr/local/anaconda3/lib/python3.11/site-packages/matplotlib/__init__.py", line 843, in _open_file_or_url
    with open(fname, encoding='utf-8') as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'plotting.mplstyle'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/anupkaul/akaul_git/nlp_transformer/transformers/text_classification/./example1_datasets.py", line 2, in <module>
    setup_chapter()
  File "/Users/anupkaul/akaul_git/nlp_transformer/transformers/text_classification/utils.py", line 54, in setup_chapter
    set_plot_style()
  File "/Users/anupkaul/akaul_git/nlp_transformer/transformers/text_classification/utils.py", line 28, in set_plot_style
    plt.style.use("plotting.mplstyle")
  File "/usr/local/anaconda3/lib/python3.11/site-packages/matplotlib/style/core.py", line 139, in use
    raise OSError(
OSError: 'plotting.mplstyle' is not a valid package style, path of style file, URL of style file, or library style name (library styles are listed in `style.available`)

